---
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install: 
  - docker pull o2rproject/o2r-loader:latest
  - docker pull o2rproject/o2r-muncher:latest
  - docker pull mongo:3.4 
install:
  - pip install -U pytest requests
before_script:
  - docker run --name mongodb -d -p 27017:27017 mongo:3.4
  - docker run --name testloader -d -p 8088:8088 --link mongodb:mongodb -v $HOME:/tmp/o2r -e LOADER_MONGODB=mongodb://mongodb:27017 -e DEBUG=* o2rproject/o2r-loader:latest
  - docker run --name testmuncher -d -p 8080:8080 --link mongodb:mongodb -v $HOME:/tmp/o2r -v /var/run/docker.sock:/var/run/docker.sock -e MUNCHER_MONGODB=mongodb://mongodb:27017 -e DEBUG=muncher,muncher:* o2rproject/o2r-muncher:latest
  - docker build --tag shipper .
  - "docker run --name testshipper -t -d -p 8087:8087 --link mongodb:mongodb -v $HOME:/tmp/o2r -e SHIPPER_REPO_TOKENS='{\"Download\": \"\"}' -e SHIPPER_BOTTLE_HOST=0.0.0.0 -e SHIPPER_MONGODB=mongodb://mongodb:27017/ shipper"
  - sleep 10
script:
  - pytest
after_failure:
  - sleep 5
  - docker logs testloader
  - docker logs testmuncher
  - docker logs testshipper
notifications:
  email: false
